name: researcher

description: Example demonstrating how to use the library merging_builder.

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  researcher_builder:
    path: ../researcher_builder

dev_dependencies:
  build_runner: ^2.1.5
  build_test: ^2.1.4
  lints: ^1.0.1
  source_gen: ^1.1.1
  test: ^1.19.3
