name: researcher_builder

description: Example demonstrating how to use the library merging_builder.

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  analyzer: ^6.2.0
  build: ^2.1.1
  build_config: ^1.0.0
  merging_builder_svb:
    path: ../../
  quote_buffer: ^0.2.3
  researcher:
    path: ../researcher
  source_gen: ^1.1.1

dev_dependencies:
  lints: ^1.0.1
